export const defaultTheme = {
  '--base---white': '#FFFFFF',
  '--base---background': '#FAFAFA',
  '--base---card': '#F3F2F2',
  '--base---input': '#EDEDED',
  '--base---button': '#E6E5E5',
  '--base---hover': '#D7D5D5',
  '--base---label': '#8D8686',
  '--base---text': '#574F4D',
  '--base---subtitle': '#403937',
  '--base---title': '#272221',

  '--brand---purple--dark': '#4B2995',
  '--brand---purple': '#8047F8',
  '--brand---purple--light': '#EBE5F9',
  '--brand---yellow--dark': '#C47F17',
  '--brand---yellow': '#DBAC2C',
  '--brand---yellow--light': '#F1E9C9',
  '--title---title--x-l': '3rem',
  '--title---title--l': '2rem',
  '--title---title--m': '1.5rem',
  '--title---title--s': '1.25rem',
  '--title---title--x-s': '1.12rem',

  '--text---regular--l': '1.25rem',
  '--text---bold--l': '1.25rem',
  '--text---regular--m': '1rem',
  '--text---bold--m': '1rem',
  '--text---regular--s': '0.88rem',
  '--text---bold--s': '0.75rem',

  '--components---tag': '0.62rem',
  '--components---button--g': '0.88rem',
  '--components---button--s': '0.75rem',

  '--font---title': '"Baloo 2", cursive',
  '--font---text': '"Roboto", sans-serif',
}
